- .github/workflows/release-pr.yml
`GITHUB_TOKEN` is provided to workflows by default, no need to provide it ourselves
> Remove extraneous github token

- tsconfig.build.json
The top-level tsconfig is missing references to some of the packages, this adds the ones that are missing. Spotted by @glasser 🙇
> Add missing project references

- .changeset/big-oranges-rush.md
- packages/keyValueCache/package.json
- packages/keyvAdapter/package.json
Whoops. I think I had originally intended the `keyvaluecache` package to be just types and forgot to add an entry point. Then copy/pasted that mistake into `keyvadapter`.
> Fix entry points for new caching packages

- .changeset/giant-crabs-sing.md
- packages/keyvAdapter/src/__tests__/KeyvAdapter.test.ts
- packages/keyvAdapter/src/index.ts
Hello,
This PR adds typescript class generics to match `Keyv` class generics. 
This is required to match typing for `Keyv` instances with generics such as `new Keyv<any, RedisOptions>(...)`
For example if initializing `KeyvAdapter` as:
```ts
import { KeyvAdapter } from '@apollo/utils.keyvadapter';
import Keyv from 'keyv';
import { RedisOptions } from 'ioredis';
new KeyvAdapter<any>(
new Keyv<any, RedisOptions>('redis://user:pass@localhost:6379', {
sentinels: [],
}),
) 
```
typescript would complain as:
With this PR, `KeyvAdapter` can be initiated with generics as:
```ts
import { KeyvAdapter } from '@apollo/utils.keyvadapter';
import Keyv from 'keyv';
import { RedisOptions } from 'ioredis';
new KeyvAdapter<any, RedisOptions>( // <- changes
new Keyv<any, …
```
> fix(keyvAdapter): update generics to match Keyv

- .changeset/tiny-tools-invent.md
- package-lock.json
- packages/cache-control-types/.npmignore
- packages/cache-control-types/LICENSE
- packages/cache-control-types/README.md
- packages/cache-control-types/package.json
- packages/cache-control-types/src/index.ts
- packages/cache-control-types/tsconfig.json
- tsconfig.build.json
This package will move to the apollo-server repo once v4.0.0 is
released, but we're putting it here for now so we can do a non-alpha
release.
This will allow us to (among other things) remove the use of
`apollo-server-types` in `@apollo/subgraph`, and remove the `declare
module` in AS4 that would conflict with the AS3 version if both versions
end up installed in a single TS project.
Note that the `CacheAnnotation` type is not moved into this package;
instead, it will become an internal implementation detail of the cache
control plugin.
> New package: @apollo/cache-control-types

- .changeset/sharp-suns-boil.md
- package-lock.json
- packages/server-gateway-interface/.npmignore
- packages/server-gateway-interface/README.md
- packages/server-gateway-interface/package.json
- packages/server-gateway-interface/src/index.ts
- packages/server-gateway-interface/tsconfig.json
- tsconfig.build.json
This package was reviewed in
https://github.com/apollographql/apollo-server/pull/6771
> New package @apollo/server-gateway-interface

- package-lock.json
- package.json
The current version provides its own types; this is an empty package. (Noticed it warning.)
> chore(deps): remove stub @types/lru-cache type definition

- .changeset/weak-pots-sneeze.md
- packages/server-gateway-interface/package.json
We still need to support Node 12 for gateway 0.x.
> @apollo/server-gateway-interface: support Node 12

- package.json
- tsconfig.test.base.json
For whatever reason, Jest was happy with this (perhaps it implicitly
builds with skipLibCheck?) but you couldn't use `tsc`.
> Make tsc capable of building tests, and check before running tests

- .changeset/orange-beers-burn.md
- packages/fetcher/src/index.ts
See the comment for an explanation of why we gave up on providing a more
precise definition. We think this will work correctly with most existing
fetch and AbortController implementations.
> fetcher: add optional `signal?: any` to support aborting fetches

- .changeset/tough-tigers-roll.md
- packages/server-gateway-interface/src/index.ts
The consumer of this in `@apollo/gateway` is already doing some weird
stuff with `Omit` around this field, so just explicitly allow the AS2
case.
See https://github.com/apollographql/federation/issues/2077
> server-gateway-interface: work with AS2 too

- .changeset/silent-rocks-punch.md
- packages/fetcher/package.json
- packages/logger/package.json
- packages/withRequired/package.json
The `"main": ""` approach is employed by DefinitelyTyped packages as a means to support types-only packages being importable in both CJS and ESM contexts. (as seen here, for example: https://unpkg.com/@types/make-fetch-happen@10.0.0/package.json)
Fixes https://github.com/apollographql/apollo-utils/issues/207
> Add ESM support for types-only packages

- .changeset/curly-plants-serve.md
- .circleci/config.yml
- package-lock.json
- package.json
- packages/createHash/package.json
- packages/dropUnusedDefinitions/package.json
- packages/fetcher/package.json
- packages/isNodeLike/package.json
- packages/jestGraphQLASTSerializer/package.json
- packages/keyValueCache/package.json
- packages/keyvAdapter/package.json
- packages/logger/package.json
- packages/operationRegistrySignature/package.json
- packages/printWithReducedWhitespace/package.json
- packages/removeAliases/package.json
- packages/sortAST/package.json
- packages/stripSensitiveLiterals/package.json
- packages/usageReporting/package.json
- packages/withRequired/package.json
Node v12 is now EOL, we should drop support for it.
Testing against Node v12 is currently blocking some major upgrades:
https://github.com/apollographql/apollo-utils/pull/193
https://github.com/apollographql/apollo-utils/pull/206
> Drop support for Node 12

- .changeset/plenty-cats-return.md
- package-lock.json
- package.json
- packages/keyValueCache/package.json
- renovate.json5
Introduced as a consequence of the renovate config I created:
cab3444fa06e7ecc0e1918807d9578869407d65b (from #169)
Issue raised by @SimenB here:
https://github.com/apollographql/apollo-utils/pull/169#discussion_r1030190816
This PR also updates the `@types/node` version to 14, which should've been done as part of dropping node 12 support and happens to be a requirement for this PR.
> Fix specified `lru-cache` version range and update `@types/node` version

- .changeset/red-bags-pump.md
- packages/keyValueCache/README.md
- packages/keyValueCache/src/PrefixingKeyValueCache.ts
- packages/keyValueCache/src/__tests__/PrefixingKeyValueCache.test.ts
- packages/keyValueCache/src/index.ts
This allows software like Apollo Server plugins to "prefix" their provided cache by default, but still allow you to disable prefixes by passing in a specially "tagged" cache.
Part of apollographql/apollo-server#6742. Will close that issue once AS is updated to throw if one of these caches is provided to it. Also part of apollographql/datasource-rest#19.
> keyvaluecache: add PrefixesAreUnnecessaryForIsolationCache

- .changeset/yellow-dogs-do.md
- packages/keyvAdapter/src/__tests__/KeyvAdapter.test.ts
- packages/keyvAdapter/src/index.ts
Fixes #256
As mentioned in the above issue, `KeyvAdapter` currently provides an invalid function to `DataLoader`. Though the types don't indicate it, `keyv.get(keys)`(the plural/array overload) is capable of returning `undefined` in the event that the underlying `Store.getMany` returns `undefined`. When this happens, `KeyvAdapter` violates `DataLoader`s expectations (and it throws an error).
We can defend against this by handling the `undefined` case and returning an array of `keys.length` filled with `undefined`.
> Enforce `DataLoader` contract

- .changeset/selfish-knives-flow.md
- package-lock.json
- packages/generate-persisted-query-manifest/package.json
- packages/persisted-query-lists/package.json
When installing the packages to extract the manifest file, npm would warn about the incorrect peer dependency version. This PR ensure the current `v3.8.0` alpha and beta releases can also be used.
> Allow v3.8.0 prerelease versions of `@apollo/client`

- .changeset/moody-pots-promise.md
- package-lock.json
- packages/generate-persisted-query-manifest/cli.js
- packages/generate-persisted-query-manifest/package.json
- packages/generate-persisted-query-manifest/src/index.ts
The CLI can now take a config file that will be used for the operation extraction. The CLI uses [`cosmiconfig`](https://github.com/cosmiconfig/cosmiconfig) and will, by default, search for a config file in these locations:
const supportedExtensions = ["json", "yml", "yaml", "js", "ts", "cjs"];
- `.persisted-query-manifest.config.json`
- `persisted-query-manifest.config.json`
- `.persisted-query-manifest.config.yml`
- `persisted-query-manifest.config.yml`
- `.persisted-query-manifest.config.yaml`
- `persisted-query-manifest.config.yaml`
- `.persisted-query-manifest.config.js`
- `persisted-query-manifest.config.js`
- `.persisted-query-manifest.config.ts`
- `persisted-query-manifest.config.ts`
- `.persisted-query-manifest.config.cjs`
- `persisted-query-manifest.config.cjs`
Or a …
> Add support for a config file to the `generate-persisted-query-manifeest` CLI

- .changeset/yellow-clouds-taste.md
- package-lock.json
- packages/usageReporting/package.json
This dependency update adds support the `ConditionNode`. Currently, the gateway interface package already has this update. When Apollo Server and Gateway are run in tandem this can lead to duplicate / conflicting versions of the `@apollo/usage-reporting-protobuf` package being installed under specific circumstances. This version bump ensures that users running the latest versions of these packages don't run into this.
> Update usage reporting protobuf dependency

- .changeset/yellow-clouds-taste.md
- package-lock.json
- packages/usageReporting/package.json
This dependency update adds support the `ConditionNode`. Currently, the gateway interface package already has this update. When Apollo Server and Gateway are run in tandem this can lead to duplicate / conflicting versions of the `@apollo/usage-reporting-protobuf` package being installed under specific circumstances. This version bump ensures that users running the latest versions of these packages don't run into this.
Backport of #299
> Update usage reporting protobuf dependency (version 2 backport)

- .changeset/weak-monkeys-reflect.md
- package-lock.json
- packages/generate-persisted-query-manifest/package.json
- packages/generate-persisted-query-manifest/src/@types/vfile-reporter.d.ts
- packages/generate-persisted-query-manifest/src/index.ts
Rather than erroring on the first encountered error, this PR will collect all errors up-front then report them at the same time. This also changes the format of the error to make it super clear which file the error was from.
**Before**
**After**
> Better error handling

- .changeset/strong-eyes-play.md
- packages/persisted-query-lists/src/__tests__/persistedQueryLists.test.ts
- packages/persisted-query-lists/src/index.ts
The `createPersistedQueryManifestVerificationLink` previously took several options for handling failed verifications:
- `onAnonymousOperation`
- `onMultiOperationDocument`
- `onNoOperationsDocument`
- `onUnknownOperationName`
- `onDifferentBody`
While this worked, this creates a large burden on the developer to remember to add a callback for each callback or risk missing some notifications. Adding additional checks in the future also means additional callbacks.
Instead, this PR conslidates the failures down to a single `onVerificationFailed` handler with a `reason` field that describes the verification that failed.
> Conslidate verification failure callbacks in `createPersistedQueryManifestVerificationLink` to single `onFailedVerfication` callback

- .changeset/twenty-ligers-sip.md
- packages/generate-persisted-query-manifest/cli.js
- packages/generate-persisted-query-manifest/src/index.ts
The `generate-persisted-query-manifest` CLI now has the ability to generate custom manifest operation IDs. When using a config file format that supports functions (i.e. `js` and `ts` extensions), a `createCustomId` function can be added to customize how the ID should be generated for a given query.
Here is an example that shows how to create a base64 encoded ID of the query when its operation name is `TestOperation`:
```ts
// persisted-query-manifest.config.ts
import { PersistedQueryManifestConfig } from '@apollo/generate-persisted-query-manifest';
import { Buffer } from 'node:buffer'
const config: PersistedQueryManifestConfig = {
createOperationId(query, { operationName, createDefaultId }) {
switch (operationName) {
case 'TestOperation':
return Buffer.from(query).toString('base64'); …
```
> Add ability create custom manifest operation IDs

- packages/persisted-query-lists/src/__tests__/persistedQueryLists.test.ts
- packages/persisted-query-lists/src/index.ts
Adds the ability to load the persisted query manifest synchronously. In case someone already has the manifest loaded for other reasons, it can now be passed directly to both `createPersistedQueryManifestVerificationLink` and `generatePersistedQueryIdsFromManifest`
> Allow persisted query manifest to be loaded synchronously

- .changeset/fifty-gorillas-sell.md
- package-lock.json
- packages/generate-persisted-query-manifest/README.md
- packages/generate-persisted-query-manifest/package.json
- packages/generate-persisted-query-manifest/src/index.ts
Removes the `documentIgnorePatterns` in favor of `documents`. This switches the underlying glob parsing library from `glob` to `globby`.
> Consolidate `documents` and `documentIgnorePatterns` in manifest config

- packages/persisted-query-lists/README.md
Adds documentation for the exported utilities from `@apollo/persisted-query-lists`.
[Rendered](https://github.com/apollographql/apollo-utils/blob/document-query-lists/packages/persisted-query-lists/README.md)
> Add documentation for `@apollo/persisted-query-lists`

- packages/generate-persisted-query-manifest/README.md
We considered changing the code so that paths are interpreted relative to the directory containing the config file. We noted that graphql-code-generator works the same way that we currently work, so that seems good enough.
> generate-persisted-query-manifest: clarify use of relative paths

- package-lock.json
- packages/generate-persisted-query-manifest/package.json
- packages/generate-persisted-query-manifest/src/__tests__/cli.test.ts
- packages/generate-persisted-query-manifest/src/__tests__/generatePersistedQueryManifest.test.ts
Adds a full test suite for the CLI for the `@apollo/generate-persisted-query-manifest` package.
> Add tests for existing functionality in generate-persisted-query-manifest

- .changeset/poor-flowers-sin.md
- packages/generate-persisted-query-manifest/cli.js
- packages/generate-persisted-query-manifest/src/__tests__/cli.test.ts
- packages/generate-persisted-query-manifest/src/index.ts
Adds a `--list-files` option to the CLI that will print the list of files matched against the configured `documents` pattern. This can be useful for debugging why the command may or may not be including/not including specific queries in the manifest.
> Add CLI option to `generate-persisted-query-manifest` that lists all matched files using the `documents` pattern

- jest.config.base.ts
- package-lock.json
- package.json
Prettier v3 is currently not compatible with Jest inline snapshots (https://github.com/jestjs/jest/issues/14305). When trying to use an inline snapshot, the following error is displayed:
```
FAIL   generate-persisted-query-manifest  packages/generate-persisted-query-manifest/src/__tests__/cli.test.ts
● Test suite failed to run
Jest: Inline Snapshots are not supported when using Prettier 3.0.0 or above.
See https://jestjs.io/docs/configuration/#prettierpath-string for alternatives.
at saveInlineSnapshots (../../node_modules/jest-snapshot/build/InlineSnapshots.js:101:15)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        10.524 s
Ran all test suites matching /packages\/generate-persisted-query-manifest\//i.
```
This PR adds the suggestion in the [Jest …
> Adds prettier v2 for Jest to get inline snapshots working again

- .changeset/violet-zoos-shout.md
- packages/generate-persisted-query-manifest/cli.js
- packages/generate-persisted-query-manifest/src/__tests__/cli.test.ts
When generating a persisted query manifest file, its possible that no operations were found during manifest generation, which could be due to a misconfiguration of the glob pattern used to search for operations. Currently the user has to run the command, then open the manifest file to see if operations were added which can be pretty cumbersome. This PR updates the terminal output to list the number of matched operations. If none were found, a warning is displayed as well.
> Log warning when no operations are found and add number of operations matched during generation

- .changeset/nice-boats-shake.md
- packages/fetcher/src/index.ts
Was present in previous Apollo REST Data Source versions, but seems to be missing on this one. It's part of the Fetch API (https://developer.mozilla.org/en-US/docs/Web/API/Request/redirect), so it should be safe to add here.
> Add `redirect` to `FetcherRequestInit`

- .changeset/dirty-masks-nail.md
- package-lock.json
- packages/generate-persisted-query-manifest/README.md
- packages/generate-persisted-query-manifest/package.json
- packages/generate-persisted-query-manifest/src/__tests__/cli.test.ts
- packages/generate-persisted-query-manifest/src/__tests__/tsconfig.json
- packages/generate-persisted-query-manifest/src/index.ts
- packages/generate-persisted-query-manifest/tsconfig.json
Apollo Client v3.8 added support for [custom document transforms](https://www.apollographql.com/docs/react/data/document-transforms) that can be used to modify queries before they are sent to the server. This PR adds support for this feature during manifest generation to ensure the queries saved to the manifest match what will be sent by the client in a running app.
> Add ability to specify custom document transform during manifest generation

- .changeset/khaki-birds-tap.md
- .changeset/perfect-lies-protect.md
- package-lock.json
- packages/generate-persisted-query-manifest/package.json
- packages/generate-persisted-query-manifest/src/__tests__/cli.test.ts
- packages/generate-persisted-query-manifest/src/index.ts
Fixes #431
Better reports errors if they originate from Apollo Client itself rather than throwing an obscure error during the manifest generation. This change also adds detects multiple operations in a single document and will report those as errors.
> Better handle errors from the client and detect multiple operations

- .changeset/afraid-badgers-glow.md
- package-lock.json
- packages/keyvAdapter/README.md
- packages/keyvAdapter/package.json
- packages/keyvAdapter/src/__tests__/KeyvAdapter.test.ts
- packages/keyvAdapter/src/index.ts
This implements support for keyv version 5, which fixes #457 and #459.
> Added keyv 5 support for KeyvAdapter

- .changeset/early-boxes-check.md
- packages/createHash/src/index.ts
Apparently Next.JS "Turbopack" runs code in a weird semi-Node environment that doesn't have module.require. We don't want to call require directly because that makes other bundlers put in polyfills. So make Turbopack use sha.js instead of just throwing. Non-ideal but better than what we have today.
For apollographql/apollo-server#8004
> createhash: only call module.require if it exists

- .changeset/early-boxes-check.md
- packages/createHash/src/index.ts
> [backport v2] `createhash` Support Turbopack 
